version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: drone-tracker-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: dronetracker
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5439:5432"

volumes:
  postgres-data:
